USE [master]
GO

/****** Object:  Database [FabricAid_Dev]    Script Date: 2017/02/27 10:10:28 AM ******/
CREATE DATABASE [FabricAid_Dev]
 CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'FabricAid_Dev', FILENAME = N'C:\Data\FabricAid_Dev.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON
( NAME = N'FabricAid_Dev_log', FILENAME = N'C:\Data\FabricAid_Dev_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 1024KB )
GO

ALTER DATABASE [FabricAid_Dev] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FabricAid_Dev].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FabricAid_Dev] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [FabricAid_Dev] SET ANSI_NULLS OFF
GO

ALTER DATABASE [FabricAid_Dev] SET ANSI_PADDING OFF
GO

ALTER DATABASE [FabricAid_Dev] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [FabricAid_Dev] SET ARITHABORT OFF
GO

ALTER DATABASE [FabricAid_Dev] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [FabricAid_Dev] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [FabricAid_Dev] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [FabricAid_Dev] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [FabricAid_Dev] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [FabricAid_Dev] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [FabricAid_Dev] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [FabricAid_Dev] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [FabricAid_Dev] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [FabricAid_Dev] SET  DISABLE_BROKER
GO

ALTER DATABASE [FabricAid_Dev] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [FabricAid_Dev] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [FabricAid_Dev] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [FabricAid_Dev] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [FabricAid_Dev] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [FabricAid_Dev] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [FabricAid_Dev] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [FabricAid_Dev] SET RECOVERY SIMPLE
GO

ALTER DATABASE [FabricAid_Dev] SET  MULTI_USER
GO

ALTER DATABASE [FabricAid_Dev] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [FabricAid_Dev] SET DB_CHAINING OFF
GO

ALTER DATABASE [FabricAid_Dev] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [FabricAid_Dev] SET TARGET_RECOVERY_TIME = 0 SECONDS
GO

ALTER DATABASE [FabricAid_Dev] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [FabricAid_Dev] SET  READ_WRITE
GO
