USE [master]
GO

/****** Object:  Database [FabricAid]    Script Date: 2017/03/13 13:27:49 ******/
CREATE DATABASE [FabricAid]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FabricAid', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS01\MSSQL\DATA\FabricAid.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FabricAid_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS01\MSSQL\DATA\FabricAid_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [FabricAid] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FabricAid].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FabricAid] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FabricAid] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FabricAid] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FabricAid] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FabricAid] SET ARITHABORT OFF 
GO

ALTER DATABASE [FabricAid] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FabricAid] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FabricAid] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FabricAid] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FabricAid] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FabricAid] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FabricAid] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FabricAid] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FabricAid] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FabricAid] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FabricAid] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FabricAid] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FabricAid] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FabricAid] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FabricAid] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FabricAid] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FabricAid] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FabricAid] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FabricAid] SET  MULTI_USER 
GO

ALTER DATABASE [FabricAid] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FabricAid] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FabricAid] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FabricAid] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FabricAid] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FabricAid] SET QUERY_STORE = OFF
GO

USE [FabricAid]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [FabricAid] SET  READ_WRITE 
GO

